name: Validação de Links
on:
  push:
    branches: [ main, workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./Actions/Validation
      run: swift build -v
    - name: Run tests
      working-directory: ./Actions/Validation
      run: swift test -v
